services:
  postgres:
    image: 'postgres:latest'
    networks:
      - webrise-network
    environment:
      - 'POSTGRES_DB=webriseDB'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=webreiseUser'
    ports:
      - '5432:5432'

  webrise_api:
    build: .
    networks:
      - webrise-network
    depends_on:
      - postgres
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/webriseDB'
      - 'SPRING_DATASOURCE_USERNAME=webreiseUser'
      - 'SPRING_DATASOURCE_PASSWORD=secret'
    ports:
      - '9876:9876'

networks:
  webrise-network:
    driver: bridge
